export default {
  surName: '',
  firstName: '',
  middleName: '',
  dataBirth: '',
  email: '',
  gender: 'male',
  citizenship: '',
  changeSurname: 'no',
  oldSurName: '',
  oldFirstName: '',
  serialPassport: '',
  numberPassport: '',
  dataIssuePassport: '',
  inoFirstName: '',
  inoSurName: '',
  inoNumberPassport: '',
  inoCountryIssue: '',
  inoTypePassport: '',
  citizenshipCustom: '',
}